# Generated by Django 5.2.4 on 2025-09-26 04:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authsystem', '0005_alter_profession_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('labour', 'Labour'), ('customer', 'Customer')], max_length=10)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authsystem.customer')),
                ('labour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authsystem.labour')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
