# Generated by Django 5.2.4 on 2025-07-20 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authsystem', '0003_alter_labour_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_username', models.CharField(max_length=100)),
                ('date', models.DateField(unique=True)),
                ('location_name', models.CharField(max_length=100)),
                ('b_address', models.TextField()),
                ('confirm', models.BooleanField(default=False)),
                ('labour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authsystem.labour')),
            ],
        ),
    ]
