# Generated by Django 5.2.4 on 2025-09-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='b_fees',
            field=models.CharField(default=0, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='b_profession',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
