# Generated by Django 5.2.4 on 2025-09-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_book_b_fees_book_b_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='lab_username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
