# Generated by Django 5.2.4 on 2025-09-03 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0005_alter_profession_fees'),
        ('customer', '0003_book_lab_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cust_username',
        ),
        migrations.AddField(
            model_name='book',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authsystem.customer'),
        ),
    ]
