# Generated by Django 5.2.4 on 2025-07-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour',
            name='verification',
            field=models.BooleanField(default=False),
        ),
    ]
