# Generated by Django 5.2.4 on 2025-07-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0002_labour_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labour',
            name='image',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
