# Generated by Django 5.2.4 on 2025-09-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0003_alter_labour_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labour',
            name='fees',
        ),
        migrations.AddField(
            model_name='profession',
            name='fees',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
