# Generated by Django 5.2.4 on 2025-09-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0004_remove_labour_fees_profession_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='fees',
            field=models.CharField(max_length=10),
        ),
    ]
